-- AlterTable
ALTER TABLE `Booking` MODIFY `status` ENUM('SEARCHED', 'SELECTED', 'REVALIDATING', 'PRICE_CONFIRMED', 'PRICE_CHANGED', 'UNAVAILABLE', 'PASSENGER_PENDING', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'BOOKING_PENDING', 'BOOKED', 'BOOKING_FAILED', 'BOOKING_UNKNOWN', 'TICKETING_PENDING', 'TICKETED', 'TICKETING_FAILED', 'TICKETING_UNKNOWN', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', 'EXPIRED') NOT NULL DEFAULT 'SEARCHED';

-- AlterTable
ALTER TABLE `BookingStatusHistory` MODIFY `fromStatus` ENUM('SEARCHED', 'SELECTED', 'REVALIDATING', 'PRICE_CONFIRMED', 'PRICE_CHANGED', 'UNAVAILABLE', 'PASSENGER_PENDING', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'BOOKING_PENDING', 'BOOKED', 'BOOKING_FAILED', 'BOOKING_UNKNOWN', 'TICKETING_PENDING', 'TICKETED', 'TICKETING_FAILED', 'TICKETING_UNKNOWN', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', 'EXPIRED') NULL;

-- AlterTable
ALTER TABLE `BookingStatusHistory` MODIFY `toStatus` ENUM('SEARCHED', 'SELECTED', 'REVALIDATING', 'PRICE_CONFIRMED', 'PRICE_CHANGED', 'UNAVAILABLE', 'PASSENGER_PENDING', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'BOOKING_PENDING', 'BOOKED', 'BOOKING_FAILED', 'BOOKING_UNKNOWN', 'TICKETING_PENDING', 'TICKETED', 'TICKETING_FAILED', 'TICKETING_UNKNOWN', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', 'EXPIRED') NOT NULL;

-- AlterTable
CREATE INDEX `Booking_providerRef_idx` ON `Booking`(`providerRef`);

-- CreateTable
CREATE TABLE `ProviderOperation` (
    `id` VARCHAR(191) NOT NULL,
    `bookingId` VARCHAR(191) NULL,
    `provider` VARCHAR(32) NOT NULL,
    `operation` ENUM('SEARCH', 'REVALIDATE', 'CREATE_BOOKING', 'GET_BOOKING_STATUS', 'ISSUE_TICKET', 'VOID_TICKET', 'CANCEL_BOOKING', 'GET_FARE_RULES', 'GET_SEAT_MAP') NOT NULL,
    `idempotencyKey` VARCHAR(128) NOT NULL,
    `correlationId` VARCHAR(64) NOT NULL,
    `providerReference` VARCHAR(64) NULL,
    `status` ENUM('STARTED', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'UNKNOWN') NOT NULL DEFAULT 'STARTED',
    `requestMetadata` JSON NULL,
    `responseMetadata` JSON NULL,
    `errorCode` VARCHAR(64) NULL,
    `errorMessage` VARCHAR(255) NULL,
    `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `completedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ProviderOperation_idempotencyKey_key`(`idempotencyKey`),
    INDEX `ProviderOperation_bookingId_operation_idx`(`bookingId`, `operation`),
    INDEX `ProviderOperation_provider_startedAt_idx`(`provider`, `startedAt`),
    INDEX `ProviderOperation_status_startedAt_idx`(`status`, `startedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ProviderOperation` ADD CONSTRAINT `ProviderOperation_bookingId_fkey` FOREIGN KEY (`bookingId`) REFERENCES `Booking`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
