export const COUNTRIES = [
  { code: "BD", name: "Bangladesh" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "QA", name: "Qatar" },
  { code: "OM", name: "Oman" },
  { code: "KW", name: "Kuwait" },
  { code: "BH", name: "Bahrain" },
  { code: "IN", name: "India" },
  { code: "PK", name: "Pakistan" },
  { code: "NP", name: "Nepal" },
  { code: "LK", name: "Sri Lanka" },
  { code: "TH", name: "Thailand" },
  { code: "MY", name: "Malaysia" },
  { code: "SG", name: "Singapore" },
  { code: "ID", name: "Indonesia" },
  { code: "CN", name: "China" },
  { code: "JP", name: "Japan" },
  { code: "TR", name: "Turkey" },
  { code: "GB", name: "United Kingdom" },
  { code: "FR", name: "France" },
  { code: "DE", name: "Germany" },
  { code: "IT", name: "Italy" },
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
] as const;

export const CITIES: Array<{ country: string; name: string; code?: string }> = [
  { country: "BD", name: "Dhaka", code: "DAC" },
  { country: "BD", name: "Chittagong", code: "CGP" },
  { country: "BD", name: "Sylhet", code: "ZYL" },
  { country: "BD", name: "Cox's Bazar", code: "CXB" },
  { country: "BD", name: "Jessore", code: "JSR" },
  { country: "BD", name: "Rajshahi", code: "RJH" },
  { country: "BD", name: "Saidpur", code: "SPD" },
  { country: "BD", name: "Barisal", code: "BZL" },
  { country: "AE", name: "Dubai", code: "DXB" },
  { country: "AE", name: "Abu Dhabi", code: "AUH" },
  { country: "AE", name: "Sharjah", code: "SHJ" },
  { country: "SA", name: "Jeddah", code: "JED" },
  { country: "SA", name: "Riyadh", code: "RUH" },
  { country: "SA", name: "Madinah", code: "MED" },
  { country: "SA", name: "Dammam", code: "DMM" },
  { country: "QA", name: "Doha", code: "DOH" },
  { country: "OM", name: "Muscat", code: "MCT" },
  { country: "KW", name: "Kuwait City", code: "KWI" },
  { country: "BH", name: "Manama", code: "BAH" },
  { country: "IN", name: "Delhi", code: "DEL" },
  { country: "IN", name: "Mumbai", code: "BOM" },
  { country: "IN", name: "Kolkata", code: "CCU" },
  { country: "IN", name: "Chennai", code: "MAA" },
  { country: "IN", name: "Bengaluru", code: "BLR" },
  { country: "PK", name: "Karachi", code: "KHI" },
  { country: "NP", name: "Kathmandu", code: "KTM" },
  { country: "LK", name: "Colombo", code: "CMB" },
  { country: "TH", name: "Bangkok", code: "BKK" },
  { country: "MY", name: "Kuala Lumpur", code: "KUL" },
  { country: "SG", name: "Singapore", code: "SIN" },
  { country: "ID", name: "Jakarta", code: "JKT" },
  { country: "CN", name: "Guangzhou", code: "CAN" },
  { country: "JP", name: "Tokyo", code: "TYO" },
  { country: "TR", name: "Istanbul", code: "IST" },
  { country: "GB", name: "London", code: "LON" },
  { country: "FR", name: "Paris", code: "PAR" },
  { country: "DE", name: "Frankfurt", code: "FRA" },
  { country: "IT", name: "Rome", code: "ROM" },
  { country: "US", name: "New York", code: "NYC" },
  { country: "CA", name: "Toronto", code: "YTO" },
  { country: "AU", name: "Sydney", code: "SYD" },
];

export const AIRPORTS: Array<{
  iata: string;
  name: string;
  city: string;
  country: string;
  timezone: string;
  popular?: boolean;
}> = [
  { iata: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka", country: "BD", timezone: "Asia/Dhaka", popular: true },
  { iata: "CGP", name: "Shah Amanat International Airport", city: "Chittagong", country: "BD", timezone: "Asia/Dhaka" },
  { iata: "ZYL", name: "Osmani International Airport", city: "Sylhet", country: "BD", timezone: "Asia/Dhaka" },
  { iata: "CXB", name: "Cox's Bazar Airport", city: "Cox's Bazar", country: "BD", timezone: "Asia/Dhaka", popular: true },
  { iata: "JSR", name: "Jessore Airport", city: "Jessore", country: "BD", timezone: "Asia/Dhaka" },
  { iata: "RJH", name: "Shah Makhdum Airport", city: "Rajshahi", country: "BD", timezone: "Asia/Dhaka" },
  { iata: "SPD", name: "Saidpur Airport", city: "Saidpur", country: "BD", timezone: "Asia/Dhaka" },
  { iata: "BZL", name: "Barisal Airport", city: "Barisal", country: "BD", timezone: "Asia/Dhaka" },
  { iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "AE", timezone: "Asia/Dubai", popular: true },
  { iata: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "AE", timezone: "Asia/Dubai", popular: true },
  { iata: "SHJ", name: "Sharjah International Airport", city: "Sharjah", country: "AE", timezone: "Asia/Dubai" },
  { iata: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "SA", timezone: "Asia/Riyadh", popular: true },
  { iata: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "SA", timezone: "Asia/Riyadh", popular: true },
  { iata: "MED", name: "Prince Mohammad bin Abdulaziz Airport", city: "Madinah", country: "SA", timezone: "Asia/Riyadh", popular: true },
  { iata: "DMM", name: "King Fahd International Airport", city: "Dammam", country: "SA", timezone: "Asia/Riyadh" },
  { iata: "DOH", name: "Hamad International Airport", city: "Doha", country: "QA", timezone: "Asia/Qatar", popular: true },
  { iata: "MCT", name: "Muscat International Airport", city: "Muscat", country: "OM", timezone: "Asia/Muscat" },
  { iata: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "KW", timezone: "Asia/Kuwait" },
  { iata: "BAH", name: "Bahrain International Airport", city: "Manama", country: "BH", timezone: "Asia/Bahrain" },
  { iata: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", country: "IN", timezone: "Asia/Kolkata", popular: true },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "IN", timezone: "Asia/Kolkata" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata", country: "IN", timezone: "Asia/Kolkata" },
  { iata: "MAA", name: "Chennai International Airport", city: "Chennai", country: "IN", timezone: "Asia/Kolkata" },
  { iata: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", country: "IN", timezone: "Asia/Kolkata" },
  { iata: "KHI", name: "Jinnah International Airport", city: "Karachi", country: "PK", timezone: "Asia/Karachi" },
  { iata: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu", country: "NP", timezone: "Asia/Kathmandu" },
  { iata: "CMB", name: "Bandaranaike International Airport", city: "Colombo", country: "LK", timezone: "Asia/Colombo" },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "TH", timezone: "Asia/Bangkok", popular: true },
  { iata: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "MY", timezone: "Asia/Kuala_Lumpur", popular: true },
  { iata: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "SG", timezone: "Asia/Singapore", popular: true },
  { iata: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "ID", timezone: "Asia/Jakarta" },
  { iata: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "CN", timezone: "Asia/Shanghai" },
  { iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "JP", timezone: "Asia/Tokyo" },
  { iata: "HND", name: "Haneda Airport", city: "Tokyo", country: "JP", timezone: "Asia/Tokyo" },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "TR", timezone: "Europe/Istanbul", popular: true },
  { iata: "LHR", name: "London Heathrow Airport", city: "London", country: "GB", timezone: "Europe/London", popular: true },
  { iata: "LGW", name: "London Gatwick Airport", city: "London", country: "GB", timezone: "Europe/London" },
  { iata: "CDG", name: "Paris Charles de Gaulle Airport", city: "Paris", country: "FR", timezone: "Europe/Paris" },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "DE", timezone: "Europe/Berlin" },
  { iata: "FCO", name: "Leonardo da Vinci International Airport", city: "Rome", country: "IT", timezone: "Europe/Rome" },
  { iata: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "US", timezone: "America/New_York" },
  { iata: "EWR", name: "Newark Liberty International Airport", city: "New York", country: "US", timezone: "America/New_York" },
  { iata: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "CA", timezone: "America/Toronto" },
  { iata: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "AU", timezone: "Australia/Sydney" },
];

export const AIRLINES: Array<{ iata: string; icao?: string; name: string }> = [
  { iata: "BG", icao: "BBC", name: "Biman Bangladesh Airlines" },
  { iata: "BS", icao: "UBG", name: "US-Bangla Airlines" },
  { iata: "VQ", icao: "NOV", name: "Novoair" },
  { iata: "2A", icao: "AWA", name: "Air Astra" },
  { iata: "EK", icao: "UAE", name: "Emirates" },
  { iata: "FZ", icao: "FDB", name: "flydubai" },
  { iata: "EY", icao: "ETD", name: "Etihad Airways" },
  { iata: "QR", icao: "QTR", name: "Qatar Airways" },
  { iata: "SV", icao: "SVA", name: "Saudia" },
  { iata: "XY", icao: "KNE", name: "flynas" },
  { iata: "G9", icao: "ABY", name: "Air Arabia" },
  { iata: "GF", icao: "GFA", name: "Gulf Air" },
  { iata: "KU", icao: "KAC", name: "Kuwait Airways" },
  { iata: "WY", icao: "OMA", name: "Oman Air" },
  { iata: "AI", icao: "AIC", name: "Air India" },
  { iata: "6E", icao: "IGO", name: "IndiGo" },
  { iata: "UL", icao: "ALK", name: "SriLankan Airlines" },
  { iata: "TG", icao: "THA", name: "Thai Airways" },
  { iata: "MH", icao: "MAS", name: "Malaysia Airlines" },
  { iata: "SQ", icao: "SIA", name: "Singapore Airlines" },
  { iata: "TK", icao: "THY", name: "Turkish Airlines" },
  { iata: "BA", icao: "BAW", name: "British Airways" },
  { iata: "AF", icao: "AFR", name: "Air France" },
  { iata: "LH", icao: "DLH", name: "Lufthansa" },
  { iata: "KL", icao: "KLM", name: "KLM" },
  { iata: "AA", icao: "AAL", name: "American Airlines" },
  { iata: "UA", icao: "UAL", name: "United Airlines" },
  { iata: "CX", icao: "CPA", name: "Cathay Pacific" },
];

export const SUPPLIERS: Array<{ name: string; type: "GDS" | "AIRLINE" | "HOTEL" | "PAYMENT" | "SMS" | "EMAIL" }> = [
  { name: "Mock Flight Provider", type: "GDS" },
  { name: "Mock Hotel Provider", type: "HOTEL" },
];
